### ISSUE TITLE
train area: add possibilty to create TrainingPlan and modify the name

### ISSUE THREAD

**Issue by TheoHollender** [lfa-info-22/site#5]
Road map : 
 - Create CreateTrainingPlan API view
 - Add view to create a training plan at /train/scheduler/create/
 - Adapt it for popup view with the link in /train/ (Optional)
 - Create ModifyTrainingPlan API view
 - Create an input at /train/scheduler/<int:id>/ that is also the main text and link it to the ModifyTrainingPlan API

**Comment by Itai12** [comment]
73a427fb0039af96e83d91a52c4c7295d5113f74
